#!/usr/bin/python

from i3pystatus import Status
status = Status(standalone=True)

status.register("clock", format="%R")
status.register("clock", format="%a %b %d")

status.register("mem", 
    format="ram {percent_used_mem}%",
    color=None,
    warn_color=None,
    alert_color=None
)

status.register("network",
    interface="wlp4s0",
    format_up="{v4}[ @ {essid}]",
    format_down="net down",
    color_up="#FFFFFF",
    color_down=None,
    dynamic_color=False,

    on_rightclick=None,
    on_upscroll=None,
    on_downscroll=None
)

status.register("mpd",
    format="{status} {filename}[{title}[, by {artist}]] {song_elapsed}/{song_length}",
    status={"pause": "paused", "play": "playing", "stop": "stopped"},
    color=None,
)

# Execute status command
status.run()
